[package]
name = "lc_2044_count_number_of_maximum_bitwise-_or_subsets"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
