[package]
name = "lc_1302_deepest_leaves_sum"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lc_98_validate_binary_search_tree = { path = "../98"}
